### PR TITLE
Switch to v9 API

### PR DESCRIPTION
**Pull request by tylermenezes**
The v8 sync API has been shut down. This PR switches the library over to the v9 sync API with several breaking changes:

- Some fields have been renamed, notably date fields are standardized with the name `[thing]_at`
- IDs are now strings instead of numbers

### CODE REVIEW

**Comment by tylermenezes** [comment]
Until this is merged, anyone using this project can use `"todoist": "tylermenezes/node-todoist#build"` in their package.json to get sync working again.

**Comment by romgrk** [comment]
Nice work. Can you increase this package version to `1.0.0`? It's a breaking change so I'd rather make it explicit.

**Comment by tylermenezes** [comment]
@romgrk updated to 1.0.0

**Comment by romgrk** [comment]
Updated & published to NPM. Thanks again.

**Pull request merged**
